theme: cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Favorite National Parks and Recommendations]
description: [I'll talk all about my favorite National Parks and the best places to go in some of them!]
